# on: push
# jobs:
#   build-node:
#     runs-on: ubuntu-latest
#     container: 16
#     steps:
#       - run: node --version
#       - run: npm --version
#       - uses: actions/checkout@v3
#       - run: npm install
#       - run: node app.js 

name: NodeJS Github Action
on: push  
jobs:
 build:
  runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v3
    - name: Use Node
    - uses: actions/setup-node@v3
    with: 
      node-version: 18
    - name: Install dependencies
      run: npm install
    - name: Run test
      run: npm test


   




