on: push  
jobs:
 build-node:
  runs-on: windows-latest
   
  steps:
   - run: actions/checkout@v3 # checkout the repository
   - name: Use Node

   - run: actions/setup-node@v3
     with: 
          node-version: 16
   - name: Install dependencies
     run: npm install
   - name: Run test
     run: npm test         

   




